/**
 * Represents a single interview question generated by the AI.
 */
export interface Question {
  /** Optional category for the question (e.g., "Behavioral", "Situational"). */
  category?: string;
  /** The actual text of the interview question. */
  question: string;
}

/**
 * Defines the expected structured JSON response from the backend API.
 */
export interface GenerateQuestionsResponse {
  /** Array of generated questions. */
  questions: Question[];
}

// Retrieve the base URL of the backend from environment variables.
// In Vite, environment variables are exposed via `import.meta.env`.
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

// Ensure the application fails fast if the necessary environment variable is missing.
if (!API_BASE_URL) {
  throw new Error("VITE_API_BASE_URL is not defined in the environment variables.");
}

/**
 * Calls the backend API to generate interview questions for a specific job title.
 *
 * @param jobTitle - The job title for which to generate questions.
 * @returns A promise resolving to an array of generated Question objects.
 * @throws Will throw an error if the network request fails or returns a non-ok status.
 */
export async function generateQuestions(jobTitle: string): Promise<Question[]> {
  // Execute a POST request to the backend endpoint.
  const response = await fetch(`${API_BASE_URL}/questions`, {
    method: 'POST',
    headers: {
      // Indicate that we are sending JSON data.
      'Content-Type': 'application/json',
    },
    // Serialize the payload to JSON.
    body: JSON.stringify({ job_title: jobTitle }),
  });

  // Check if the response indicates success (status 200-299).
  if (!response.ok) {
    throw new Error('Failed to generate questions. Please try again later.');
  }

  // Parse the structured JSON response returned by the backend.
  const data: GenerateQuestionsResponse = await response.json();
  
  // Return the extracted array of questions.
  return data.questions;
}
